server:
  forward-headers-strategy: framework
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  cloud:
    aws:
      cloudwatch:
        enabled: ${LETTERPICK_CLOUDWATCH_METRICS_ENABLED:false}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate

management:
  cloudwatch:
    metrics:
      export:
        namespace: ${LETTERPICK_CLOUDWATCH_METRICS_NAMESPACE:LetterPick/Dev/Application}

newsletter:
  public-feed:
    collector-inbox-address: omcxewctypxo@inbound-dev.letterpicknews.com
